### ISSUE TITLE
structure of repository

### ISSUE THREAD

**Issue by z3dev** [jscad/sample-files#1]
Let me know if you have any preferences on the structure of the repository.

I'm thinking something like this.

amf
    ...
dxf
   ...
stl
   ...

And when we import from another system then we add a specific directory. This keeps standard test files separate from other files. For example,

dxf/autocad2017

**Comment by kaosat-dev** [comment]
sure, I am ok with that 
btw , I just added a PR for boilerplate stuff, do you want to merge ?
